name: Feature request
description: "Suggest an idea for this project."
title: "[Feature Request]: "
labels:
  - "feature-request"

body:
  - type: markdown
    attributes:
      value: |
        Thank you for your suggestion!  
        Please provide a clear and concise description of your idea.

  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: "What is the core idea or problem you'd like to solve?"
      placeholder: |
        Example:
        - A brief overview of the problem or idea
        - Why is this feature important to you or others?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "Proposed Solution"
      description: "How do you imagine this feature or enhancement working?"
      placeholder: |
        Example:
        - Potential UI changes or API modifications
        - Data flow or architectural approach
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Add any other context, screenshots, or references that help illustrate the request."
    validations:
      required: false