name: Documentation Request
description: "Request updates or additions to the project documentation."
title: "[Docs]: "
labels:
  - documentation
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping us improve our documentation!
        Please provide details about the documentation issue or request.
  - type: textarea
    id: docs_section
    attributes:
      label: "Affected Documentation Section"
      description: "Which part of the docs are you referring to (e.g., README, API docs, user guide)?"
      placeholder: "e.g., Installation instructions..."
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: "Details / Suggested Improvements"
      description: "Describe what is missing or unclear and what improvements you suggest."
      placeholder: "e.g., The installation steps could be more detailed..."
    validations:
      required: true