blank_issues_enabled: false
contact_links:
  - name: "Security Vulnerabilities"
    url: "mailto:arman.avanesyan@yahoo.com"
    about: "Please report security concerns or vulnerabilities via this email."
  - name: GitHub Community Support
    url: https://github.com/ArmanAvanesyan/DFD-PlantUML/discussions/new
    about: Please ask and answer questions here.
