name: "Feature Category"
description: "Create a new feature category for CPPM"
title: "[FEATURE CATEGORY] - "
labels:
  - "feature-category"
body:
  - type: input
    id: category_title
    attributes:
      label: "Title"
      placeholder: "e.g., Centralized Data Management"
    validations:
      required: true
  - type: textarea
    id: category_description
    attributes:
      label: "Description"
      placeholder: "Provide a brief description of what this category covers (user pain points, overarching goals, etc.)."
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Features in this Category
        Please list the features that belong to this category. You can add them as markdown links or a simple list:
        - [Feature 1](link)
        - [Feature 2](link)
