name: "Feature Category"
description: "Create a new feature category for CPPM"
title: "[FEATURE CATEGORY] - "
labels:
  - "feature-category"
body:
  - type: textarea
    id: category_description
    attributes:
      label: "Description"
      placeholder: "Provide a brief description of what this category covers (user pain points, overarching goals, etc.)."
    validations:
      required: false
  - type: dropdown
    id: feature_status
    attributes:
      label: "Status"
      description: "Select the current status of this feature category."
      options:
        - "LATER"
        - "NEXT"
        - "NOW"
        - "DONE"
      default: "LATER"
    validations:
      required: true
