name: "Feature Category"
description: "Create a new feature category for CPPM"
title: "[FEATURE CATEGORY] - "
labels:
  - "feature-category"
body:
  - type: textarea
    id: category_description
    attributes:
      label: "Description"
      placeholder: "Provide a brief description of what this category covers (user pain points, overarching goals, etc.)."
    validations:
      required: true
