name: "Feature"
description: "Create or update a feature for CPPM"
title: "[FEATURE] - "
labels:
  - "feature"
body:
  - type: input
    id: parent_feature_category
    attributes:
      label: "Parent Issue"
      description:  "Replace <issue_number> with a link to any related Feature Category or higher-level issue"
      placeholder:  "#<issue_number>"
    validations:
      required: true
  - type: dropdown
    id: feature_priority
    attributes:
      label: "Priority"
      description: "Select the priority for this feature."
      options:
        - High
        - Medium
        - Low
    validations:
      required: true
  - type: textarea
    id: feature_description
    attributes:
      label: "Description"
      placeholder: "Provide a brief description of what this feature does, including context (user persona, pain points, motivation, etc.)."
    validations:
      required: true
  - type: textarea
    id: feature_functional_requirements
    attributes:
      label: "Functional Requirements / Use Cases"
      placeholder: "List the linked use cases or functional requirements (e.g., UC-001: Create Profile, UC-002: Edit Profile)."
    validations:
      required: true
  - type: textarea
    id: feature_non_functional_requirements
    attributes:
      label: "Non‑Functional Requirements (NFRs)"
      placeholder: "List the related NFRs (e.g., NFR-USAB-001, NFR-PERF-001)."
    validations:
      required: false
  - type: textarea
    id: feature_constraints
    attributes:
      label: "Constraints"
      placeholder: "List any constraints (e.g., C-001: Must work offline, C-002: Format compliance)."
    validations:
      required: false
  - type: textarea
    id: feature_related_artifacts
    attributes:
      label: "Related Artifacts"
      description: "Provide links to related process models, data models, and ADRs."
      placeholder: |
        Process Models:
        - [Logical Process Model](docs/path-to-logical-process-model.md)
        - [Physical Process Model](docs/path-to-physical-process-model.md)
        
        Data Models:
        - [Conceptual Data Model](docs/path-to-conceptual-data-model.md)
        - [Logical Data Model](docs/path-to-logical-data-model.md)
        - [Physical Data Model](docs/path-to-physical-data-model.md)
    validations:
      required: false
