name: "Add Triage Label"

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  add-triage-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add triage label to issue
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["triage"]
            })