name: "Add Triage Label"

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  add-triage-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check if Issue Has Type Label
        uses: actions/github-script@v7
        id: check-labels
        with:
          script: |
            const typeLabels = ["FR", "NFR", "feature", "use-case", "constraint"];
            const labels = context.payload.issue.labels.map(label => label.name);
            // If any type label exists, do nothing.
            const hasTypeLabel = labels.some(label => typeLabels.includes(label));
            return { hasTypeLabel };
      - name: Add triage label if no type label found
        if: steps.check-labels.outputs.hasTypeLabel == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["triage"]
            });
