name: "Auto Assign Labels and Status to Issues"

on:
  issues:
    types: [opened, edited]

jobs:
  assign-labels-status:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Status
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueLabels = (context.payload.issue.labels || []).map(label => label.name.toLowerCase());
            const issueNodeId = context.payload.issue.node_id;

            if (!issueNodeId) {
              console.error("Issue Node ID is missing.");
              return;
            }

            // Default Status Mapping
            const statusMapping = {
              "later": "f75ad846",
              "next": "47fc9ee4",
              "now": "c8fab3fb",
              "done": "98236657"
            };

            let assignedStatusId = statusMapping["next"]; // Default to NEXT

            for (const label of issueLabels) {
              if (statusMapping[label]) {
                assignedStatusId = statusMapping[label];
                break;
              }
            }

            const setStatusMutation = `
              mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $value: String!) {
                updateProjectV2ItemFieldValue(input: {
                  projectId: $projectId,
                  itemId: $itemId,
                  fieldId: $fieldId,
                  value: { singleSelectOptionId: $value }
                }) {
                  projectV2Item { id }
                }
              }
            `;

            await github.graphql(setStatusMutation, {
              projectId: "PVT_kwHOBXlNW84Azyle",
              itemId: issueNodeId,
              fieldId: "PVTSSF_lAHOBXlNW84Azylezgphsmc",
              value: assignedStatusId
            });
