name: "Auto-Assign ID & Update Index"

on:
  issues:
    types: [opened, edited]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Determine Item Type
        id: parse_labels
        run: |
          LABELS=$(jq -r '.issue.labels[].name' "$GITHUB_EVENT_PATH")
          echo "Labels: $LABELS"
          TYPE="none"

          if echo "$LABELS" | grep -qi 'UseCase'; then TYPE="UseCase"; fi
          if echo "$LABELS" | grep -qi 'FR'; then TYPE="FR"; fi
          if echo "$LABELS" | grep -qi 'NFR'; then TYPE="NFR"; fi
          if echo "$LABELS" | grep -qi 'Constraint'; then TYPE="Constraint"; fi

          echo "Detected Type: $TYPE"
          echo "ITEM_TYPE=$TYPE" >> $GITHUB_ENV

      - name: Generate Next ID
        id: generate_id
        run: |
          TYPE="${{ env.ITEM_TYPE }}"
          if [ "$TYPE" = "none" ]; then exit 0; fi

          PREFIX="${TYPE:0:1}" # First letter (U for UseCase, F for FR, etc.)
          INDEX_FILE="docs/requirements/${TYPE}-index.md"
          LAST_ID=$(grep -oE "${PREFIX}-[0-9]{3}" "$INDEX_FILE" | sed "s/${PREFIX}-//" | sort -n | tail -1)

          if [ -z "$LAST_ID" ]; then NEXT=1; else NEXT=$((LAST_ID+1)); fi
          ID=$(printf "%03d" $NEXT)

          NEW_IDENTIFIER="${PREFIX}-${ID}"
          echo "NEW_IDENTIFIER=$NEW_IDENTIFIER" >> $GITHUB_ENV
          echo "INDEX_FILE=$INDEX_FILE" >> $GITHUB_ENV

      - name: Update Issue Title
        if: env.ITEM_TYPE != 'none'
        uses: actions-ecosystem/action-update-issue@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_number: ${{ github.event.issue.number }}
          title: "[${{ env.NEW_IDENTIFIER }}] ${{ github.event.issue.title }}"

      - name: Append to Index
        if: env.ITEM_TYPE != 'none'
        run: |
          INDEX_FILE="${{ env.INDEX_FILE }}"
          NEW_ID="${{ env.NEW_IDENTIFIER }}"
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          ISSUE_TITLE="${{ github.event.issue.title }}"
          CLEAN_TITLE=$(echo "$ISSUE_TITLE" | sed -E "s/^\[[A-Z]+-[0-9]+\]\s*//")

          echo "| $NEW_ID | $CLEAN_TITLE | [#$ISSUE_NUMBER](../../issues/$ISSUE_NUMBER) |" >> "$INDEX_FILE"

          cat "$INDEX_FILE"

      - name: Commit and Push
        if: env.ITEM_TYPE != 'none'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/requirements/*.md
          git commit -m "Add $NEW_ID to $ITEM_TYPE index"
          git push origin HEAD:${{ github.ref }}
