name: "Mark and Close Stale Issues/PRs"

on:
  schedule:
    - cron: "0 0 * * *"  # runs daily at midnight
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: "Mark and Close Stale Issues/PRs"
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 45
          days-before-close: 14
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          stale-issue-message: >
            This issue has been automatically marked as stale...
          stale-pr-message: >
            This pull request has been automatically marked as stale...
          close-issue-message: >
            This issue is now closed due to inactivity...
          close-pr-message: >
            This pull request is now closed due to inactivity...
          exempt-issue-labels: "pinned,security,not-stale"
          exempt-pr-labels: "pinned,security,not-stale"
          exempt-draft-pr: true